//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBS.Advice.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionType
    {
        public long ActionTypeID { get; set; }
        public string Description { get; set; }
        public bool ShowGeneralNotes { get; set; }
        public bool ShowIndemnity { get; set; }
        public bool ShowContactInfo { get; set; }
        public bool ShowJobDetails { get; set; }
        public bool ShowAdviceGiven { get; set; }
        public bool ShowInternalNotes { get; set; }
        public bool ShowNatureOfAdvice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool Internal { get; set; }
        public Nullable<bool> UserCanSetLogTimes { get; set; }
    }
}
