//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBS.Advice.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public long ActionID { get; set; }
        public long ActionTypeID { get; set; }
        public long JobID { get; set; }
        public Nullable<long> NatureOfAdviceID { get; set; }
        public string NatureOfAdviceOther { get; set; }
        public Nullable<long> IndemnityID { get; set; }
        public Nullable<long> IndemnityReasonID { get; set; }
        public string IndemnityOther { get; set; }
        public Nullable<long> ContactID { get; set; }
        public string AdviceGiven { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> EditStartDate { get; set; }
        public Nullable<System.DateTime> EditCompletedDate { get; set; }
        public string GeneralNotes { get; set; }
        public string InternalNotes { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<long> MeetingTypeID { get; set; }
        public Nullable<long> DocumentCount { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public string ExchangeGUID { get; set; }
        public Nullable<long> ResultingTaskId { get; set; }
        public string LoggedOnBehalfOf { get; set; }
        public Nullable<bool> Outbound { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> OutOfHours { get; set; }
        public Nullable<bool> ClientSatisfiedWithAdvice { get; set; }
        public Nullable<int> NumberOfEmployeesInvolved { get; set; }
        public Nullable<bool> IsKeyEvent { get; set; }
        public Nullable<long> PolicyNumberID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ActionType ActionType { get; set; }
    }
}
