//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBS.Advice.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Actions = new HashSet<Action>();
        }
    
        public long JobID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public int ClientID { get; set; }
        public Nullable<long> AdviceCardID { get; set; }
        public Nullable<long> SiteAddressID { get; set; }
        public string Subject { get; set; }
        public Nullable<long> CurrentNatureOfAdviceID { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public Nullable<long> LastActionId { get; set; }
        public Nullable<long> ContactID { get; set; }
        public bool Closed { get; set; }
        public Nullable<long> IndemnityID { get; set; }
        public bool Sensitive { get; set; }
        public string Checklist { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifyingAction { get; set; }
        public string LastModifiedReason { get; set; }
        public bool Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> LastKeyNatureOfAdviceId { get; set; }
        public Nullable<long> PolicyNumberID { get; set; }
        public bool ProActiveCallBackCreated { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
    }
}
