//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBS.Client.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCustomer
    {
        public int CustomerID { get; set; }
        public string CustomerKey { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CompanyName { get; set; }
        public string Password { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string CompanyVATNumber { get; set; }
        public Nullable<int> NumberOfStaff { get; set; }
        public Nullable<decimal> Payroll { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string CompanyMainEmail { get; set; }
        public string CompanyWebsite { get; set; }
        public int DefaultLegalLocationID { get; set; }
        public string CurrentSalesRepUserName { get; set; }
        public string CurrentHSConsultant { get; set; }
        public string CurrentPersonnelConsultant { get; set; }
        public Nullable<int> PrincipleBusinessTypeID { get; set; }
        public string CompanyNameAKA { get; set; }
        public Nullable<int> PBSIndustryTypeID { get; set; }
        public Nullable<int> CustomerGroupID { get; set; }
        public int DefaultPaymentMethodID { get; set; }
        public Nullable<bool> PrivateAndConfidential { get; set; }
        public string AssociatedClientNotes { get; set; }
        public string AssociatedClient { get; set; }
        public string OperaSalesLedger { get; set; }
        public Nullable<bool> flagHidden { get; set; }
        public Nullable<bool> DummyAccount { get; set; }
        public Nullable<int> ClientTypeID { get; set; }
        public Nullable<bool> HighPriority { get; set; }
        public Nullable<int> LeadSaleID { get; set; }
        public Nullable<int> SyncronisationStatus { get; set; }
        public Nullable<bool> HoldAllAgreements { get; set; }
        public Nullable<int> ServiceDeskID { get; set; }
        public string TradingAs { get; set; }
        public Nullable<bool> IsVATRegistered { get; set; }
        public Nullable<int> NumberOfERMUpdates { get; set; }
        public int SalesTeamID { get; set; }
    }
}
