//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBS.Portal.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long Id { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string PortalUserID { get; set; }
        public string PageSubmittedFrom { get; set; }
        public string FeedbackText { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
